-- (1) BOOK_SALES에 BOOK에 있는 CATEGORY, AUTHOR_ID, PRICE 연결 (BOOK_ID 기준)
-- (2) (1)번에서 나온 테이블에 AUTHOR에 있는 AUTHOR_NAME 연결 (AUTHOR_ID 기준)
-- (3) (2)번 테이블을  WHERE 절 사용해서 정리
-- (4) (3)번 테이블을 사용하여 TOTAL_SALES 계산
-- (5) (4)번 테이블 GROUP BY, ORDER BY로 마무리

SELECT  B.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY,
        SUM(BS.SALES * B.PRICE) as TOTAL_SALES
FROM    BOOK_SALES BS
INNER JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID
INNER JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE   TO_CHAR(BS.SALES_DATE, 'yyyy-MM') = '2022-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME
ORDER BY AUTHOR_ID,CATEGORY DESC