SELECT  MEMBER_ID,
        MEMBER_NAME,
        GENDER,
        TO_CHAR(DATE_OF_BIRTH,'yyyy-MM-dd') as DATE_OF_BIRTH
FROM    MEMBER_PROFILE
WHERE   EXTRACT(MONTH FROM DATE_OF_BIRTH) = 3 AND
        GENDER = 'W' AND
        NOT TLNO IS NULL
ORDER BY MEMBER_ID