SELECT  UGU.USER_ID,
        UGU.NICKNAME,
        SUM(PRICE) AS TOTAL_SALES
FROM    USED_GOODS_BOARD UGB
    JOIN USED_GOODS_USER UGU ON UGU.USER_ID = UGB.WRITER_ID
WHERE   UGB.STATUS = 'DONE'
GROUP BY UGU.USER_ID,
        UGU.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE)