SELECT  TO_NUMBER(TO_CHAR(DATEtIME, 'HH24')) AS HOUR,
        COUNT(animal_id) AS COUNT
FROM    ANIMAL_OUTS
WHERE   TO_CHAR(DATETIME, 'HH24:MI') BETWEEN '09:00' AND '20:00'
GROUP BY TO_CHAR(DATEtIME, 'HH24')
ORDER BY HOUR